/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mehlikahilaltozlu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {                                    

    double Muffin1 = 1.99; 
    double Muffin2 = 1.50;
    double Muffin3 = 2.10;
    double Muffin4 = 1.10;
    double Muffin5 = 2.99;
    double Muffin6 = 2.50;
       
    int purchase1;
    System.out.println(0);
    int purchase2;
    int purchase3;
    int purchase4;
    int purchase5;
    int purchase6;
       
    double value1;
    double value2;
    double value3;
    double value4;
    double value5;
    double value6;
    
    double prizeSubTotal;
    double prizeTaxes;
    double prizeGrandTotal;
   
    
    Muffin1 = Double.parseDouble(label1.getText());
    Muffin2 = Double.parseDouble(label2.getText());
    Muffin3 = Double.parseDouble(label3.getText());
    Muffin4 = Double.parseDouble(label4.getText());
    Muffin5 = Double.parseDouble(label5.getText());
    Muffin6 = Double.parseDouble(label6.getText());
    
    purchase1 = Integer.parseInt(txt1.getText()); 
    purchase2 = Integer.parseInt(txt2.getText()); 
    purchase3 = Integer.parseInt(txt3.getText()); 
    purchase4 = Integer.parseInt(txt4.getText()); 
    purchase5 = Integer.parseInt(txt5.getText()); 
    purchase6 = Integer.parseInt(txt6.getText()); 
    
    prizeSubTotal = Double.parseDouble(subtll.getText());
    prizeTaxes = Double.parseDouble(tx.getText());
    prizeGrandTotal = Double.parseDouble(grndtll.getText());
    
    value1 = Muffin1 * purchase1;
    value2 = Muffin2 * purchase2;
    value3 = Muffin3 * purchase3;
    value4 = Muffin4 * purchase4;
    value5 = Muffin5 * purchase5;
    value6 = Muffin6 * purchase6;
   
    prizeSubTotal = Math.round(value1 + value2 + value3 + value4 + value5 + value6);
    prizeTaxes = Math.round(prizeSubTotal  * 0.13);
    prizeGrandTotal = Math.round(prizeSubTotal + prizeTaxes);
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
